/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Clock: typeof import('./src/components/common/Clock.vue')['default']
    CollectionItem: typeof import('./src/components/common/collection/CollectionItem.vue')['default']
    CollectionList: typeof import('./src/components/common/collection/CollectionList.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    LinkItem: typeof import('./src/components/common/collection/LinkItem.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    SearchPanel: typeof import('./src/components/common/SearchPanel.vue')['default']
  }
}
