name: release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Build
        run: pnpm i && pnpm build

      - name: Zip Build
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: ../dist.zip
          directory: ./dist/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist.zip

      - name: Generate Changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}